### PR TITLE
Update GradingCode.py

### PR DESCRIPTION
**Pull request by jbrown02**

### CODE REVIEW

**Comment by jbrown02** [comment]
Functionality tested and verified. 10/4 Biiiiiig Texas Butters!

**Comment by jbrown02** [comment]
Functionality tested and verified. 10/4 it's Biiiiig Texas Butters!

**Comment by jbrown02** [comment]
I changed the necessary parameters so that the code should give the proper grade values.

**Comment by LuxeCapacitor** [comment]
Code works as needed! All bugs have been fixed! Thank you for your expertise!

**Pull request merged**
